name: Deploy website

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: git pull
      - name: Generate the HTML
        run: pelican content -o output -s publishconf.py
      - name: Edit some of the HTML
        run: |
          old_texts=( "Welcome!(\r\n|\r|\n)(\s+)</a>" "<p>\&copy; ([0-9]+) </p>" )
          new_texts=( "Home</a>" "<p>\&copy; \1 Richard Shi </p>" )

          for file in $(find output -name "*.html"); do
              for i in "${!old_texts[@]}"; do
                  sed -z -E -i "s#${old_texts[$i]}#${new_texts[$i]}#g" "$file"
                  sed -z -E -i "s#${old_texts[$i]}#${new_texts[$i]}#g" "$file"
              done
          done
      - name: Push to gh-pages branch
        run: |
          ghp-import output -f -b gh-pages
          git push origin gh-pages
